version: '2'
services:
  customer-service:
    container_name: customer-service
    build:
      dockerfile: Dockerfile
    image: customer-service:latest
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
networks:
  spring-cloud-network:
    driver: bridge
